```{R}
library(tidyverse)
library(tidytext)
library(dplyr)
library(stringr)
library(janeaustenr)
library(ggplot2)
```

```{r}
afinn = get_sentiments("afinn")
afinn
```
```{r}
bing = get_sentiments("bing")
bing
```
```{r}
nrc = get_sentiments("nrc")
nrc
```

```{r}
tidy_books <- austen_books() %>%
  group_by(book) %>%
  mutate(linenumber = row_number(),
         chapter = cumsum(str_detect(text, regex("^chapter [\\divxlc]", 
                                                 ignore_case = TRUE)))) %>%
  ungroup() %>%
  unnest_tokens(word, text)
tidy_books
```

```{r}
nrc_joy <- nrc %>% filter(sentiment == "joy")

tidy_books %>%
  filter(book == "Sense & Sensibility") %>%
  inner_join(nrc_joy) %>%
  count(word, sort = TRUE)
```

```{r}
ja_s <- tidy_books %>%
  inner_join(bing) %>%
  count(book, index = linenumber %/% 80, sentiment) %>%
  pivot_wider(names_from = sentiment, values_from = n, values_fill = 0) %>% 
  mutate(sentiment = positive - negative)
ja_s
```
```{r}
ggplot(ja_s, aes(index, sentiment, fill = book)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~book, ncol = 2, scales = "free_x")
```

```{r}
afinn <- tidy_books %>% 
  inner_join(get_sentiments("afinn")) %>% 
  group_by(index = linenumber %/% 80) %>% 
  summarise(sentiment = sum(value)) %>% 
  mutate(method = "AFINN")
```
```{r}
em <- tidy_books %>% 
  filter(book == "Emma")
em
```
```{r}
b_n <- bind_rows(
  em %>% 
    inner_join(bing) %>%
    mutate(method = "Bing et al."),
  em %>% 
    inner_join(nrc %>% 
                 filter(sentiment %in% c("positive", 
                                         "negative"))
    ) %>%
    mutate(method = "NRC")) %>%
  count(method, index = linenumber %/% 80, sentiment) %>%
  pivot_wider(names_from = sentiment,
              values_from = n,
              values_fill = 0) %>% 
  mutate(sentiment = positive - negative)
```

```{r}
bind_rows(afinn, 
          b_n) %>%
  ggplot(aes(index, sentiment, fill = method)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~method, ncol = 1, scales = "free_y")
```

```{r}
library(devtools)
devtools::install_github("bradleyboehmke/harrypotter", force = TRUE)
```
```{r}
library(harrypotter)
```

```{r}
goblet_of_fire[1:1]
```

```{r}
bookname <- c("The Goblet of Fire")
books <- list(goblet_of_fire)
jk <- tibble()

for(i in seq_along(bookname)) {
  
  temp <- tibble(chapter = seq_along(books[[i]]),
                  text = books[[i]]) %>%
    unnest_tokens(word, text) %>%
    
    mutate(book = bookname[i]) %>%
    select(book, everything())
  
  jk <- rbind(jk, temp)
}

jk$book <- factor(jk$book, levels = rev(bookname))

jk
```

```{r}
afinn <- jk %>%
        group_by(book) %>% 
        mutate(word_count = 1:n(),
               index = word_count %/% 500 + 1) %>% 
        inner_join(get_sentiments("afinn")) %>%
        group_by(book, index) %>%
        summarise(sentiment = sum(value)) %>%
        mutate(method = "AFINN")
afinn
```

```{r}
ll <- jk %>%
  right_join(get_sentiments("loughran")) %>%
  filter(!is.na(sentiment)) %>%
  count(sentiment, sort = TRUE)
ll
```

```{r}
ll <- bind_rows(jk %>% 
group_by(book) %>% 
                  mutate(word_count = 1:n(),
                         index = word_count %/% 500 + 1) %>%
                  inner_join(get_sentiments("loughran") %>%
                                     filter(sentiment %in% c("positive", "negative"))) %>%
                  mutate(method = "Loughran")) %>%
        count(book, method, index = index , sentiment) %>%
        ungroup() %>%
        spread(sentiment, n, fill = 0) %>%
        mutate(sentiment = positive - negative) %>%
        select(book, index, method, sentiment)
ll
```
